[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    #refreshPeriod = "0"

[".zplug"]
    type = "git-repo"
    url = "https://github.com/zplug/zplug"
