[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    #refreshPeriod = "0"

[".zplug"]
    type = "git-repo"
    url = "https://github.com/zplug/zplug"

[".zplug/repos/robbyrussell/oh-my-zsh/custom/plugins/zsh_codex"]
    type = "git-repo"
    url = "https://github.com/tom-doerr/zsh_codex"

[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:boss14420/astronvim-config.git"

